"""empty message

Revision ID: 016e2a4a1aec
Revises: 4f098143fd18
Create Date: 2023-02-02 12:16:09.874189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016e2a4a1aec'
down_revision = '4f098143fd18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries_zip_codes', 'country_iso',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('countries_zip_codes', 'id')
    op.alter_column('users', 'confirm_password',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'confirm_password',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.add_column('countries_zip_codes', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('countries_zip_codes', 'country_iso',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
