"""empty message

Revision ID: 4f098143fd18
Revises: ce06612991f0
Create Date: 2023-02-02 11:50:56.268568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f098143fd18'
down_revision = 'ce06612991f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries_zip_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('country_iso', sa.String(), nullable=True),
    sa.Column('territories', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('zip_regex', sa.String(), nullable=True),
    sa.Column('example', sa.String(), nullable=True),
    sa.Column('version_change', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('confirm_password', sa.String(length=32), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_column('users', 'confirm_password')
    op.drop_table('countries_zip_codes')
    # ### end Alembic commands ###
