"""empty message

Revision ID: 790578987482
Revises: b18821c3ce51
Create Date: 2023-02-02 12:26:59.197776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790578987482'
down_revision = 'b18821c3ce51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries_zip_codes', 'example')
    op.drop_column('countries_zip_codes', 'nothing')
    op.drop_column('countries_zip_codes', 'term')
    op.drop_column('countries_zip_codes', 'territories')
    op.drop_column('countries_zip_codes', 'version_change')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries_zip_codes', sa.Column('version_change', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('countries_zip_codes', sa.Column('territories', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('countries_zip_codes', sa.Column('term', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('countries_zip_codes', sa.Column('nothing', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('countries_zip_codes', sa.Column('example', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
