"""empty message

Revision ID: 837792972ebf
Revises: 
Create Date: 2023-02-08 20:22:27.922208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837792972ebf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries_zip_codes',
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('country_iso', sa.String(), nullable=False),
    sa.Column('zip_regex', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('country_iso')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('confirm_password', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('zip_code', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('confirm_password', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('zip_code', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('zip_code', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('location', sa.String(length=70), nullable=False),
    sa.Column('services', sa.String(length=100), nullable=False),
    sa.Column('hotel_owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_owner'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('pet_type', sa.String(length=50), nullable=False),
    sa.Column('race', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('health', sa.String(length=50), nullable=False),
    sa.Column('pet_owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('stay_date', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('pets')
    op.drop_table('hotel')
    op.drop_table('user')
    op.drop_table('owner')
    op.drop_table('countries_zip_codes')
    # ### end Alembic commands ###
