"""empty message

Revision ID: 8fd7f7e840a6
Revises: 98e401f2189f
Create Date: 2023-01-31 10:55:17.206454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd7f7e840a6'
down_revision = '98e401f2189f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('country', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('zip_code', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'country')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
