"""empty message

Revision ID: a67bcd527269
Revises: 60236e15a964
Create Date: 2023-02-27 20:10:06.406827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67bcd527269'
down_revision = '60236e15a964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'room')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('room', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
