"""empty message

Revision ID: b18821c3ce51
Revises: 016e2a4a1aec
Create Date: 2023-02-02 12:24:31.263716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18821c3ce51'
down_revision = '016e2a4a1aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries_zip_codes', sa.Column('nothing', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries_zip_codes', 'nothing')
    # ### end Alembic commands ###
