"""empty message

Revision ID: d853f8844b8b
Revises: 837792972ebf
Create Date: 2023-02-08 20:22:42.012833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd853f8844b8b'
down_revision = '837792972ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'owner', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owner', type_='unique')
    # ### end Alembic commands ###
